const NARR={
"tap":{"name":"The tap","lead":3.6,"tail":1.8,"vo":[
 {"id":"enrolled","text":"You just enrolled in your first university class."},
 {"id":"tap","text":"One tap. It feels like nothing happened."},
 {"id":"stored","text":"But that tap was written straight into the student system, the system of record: a snapshot of that moment."},
 {"id":"travel","text":"Now it's about to travel through a platform most people never see."},
 {"id":"follow","text":"Let's follow it."}]},
"in":{"name":"Into the platform","lead":0.6,"tail":1.2,"vo":[
 {"id":"systems","text":"Every system at the university keeps its own records: students, learning, people and finance."},
 {"id":"colours","text":"Think of each one as its own colour of light."},
 {"id":"events","text":"Some changes travel as events, the moment they happen."},
 {"id":"integ","text":"An integration platform routes them, retries them and keeps them secure,"},
 {"id":"zerobus","text":"and Zerobus Ingest lands them in the lakehouse within seconds."},
 {"id":"files","text":"Other data arrives in bulk, as files, like the nightly file of new offers."},
 {"id":"auto","text":"Auto Loader reads each new file exactly once, and remembers where it stopped."},
 {"id":"bronze","text":"Everything lands in bronze, exactly as it arrived."},
 {"id":"hot","text":"Only what matters right now travels hot. The rest can wait for the next delivery."}]},
"sketch":{"name":"The sketch","lead":0.6,"tail":1.4,"vo":[
 {"id":"first","text":"Before any of this can make sense, we need a sketch of the world we're trying to understand."},
 {"id":"model","text":"What is a student? A class? An enrolment? And how do they connect?"},
 {"id":"concept","text":"That's the conceptual model: agreed with the business, and written down once."},
 {"id":"wrong","text":"Get the sketch wrong, and the pieces never fit."},
 {"id":"downstream","text":"Every picture built on top of it is wrong too, no matter how clean the data is."},
 {"id":"right","text":"Get it right, and every piece has its place."}]},
"refine":{"name":"Refining with dbt","lead":0.6,"tail":1.4,"vo":[
 {"id":"recipes","text":"Now the refining starts. dbt holds the recipes: models, tests and documentation, all in version control."},
 {"id":"runs","text":"Databricks runs them, on a SQL warehouse."},
 {"id":"closer","text":"Look closer at bronze, and the pieces are rough:"},
 {"id":"rough","text":"glitches, duplicates, errors, different formats, different clocks."},
 {"id":"sources","text":"First, dbt declares each source, and checks that it's fresh."},
 {"id":"staging","text":"Staging models clean each source: clear names, one format, one clock, no duplicates."},
 {"id":"tests","text":"Tests run at every step. A missing value stops here."},
 {"id":"inter","text":"Intermediate models join the sources, exactly as the sketch says."},
 {"id":"orphan","text":"An enrolment with no matching class stops here."},
 {"id":"silver","text":"What comes out is silver: one clean, consistent picture of the university."},
 {"id":"trace","text":"And every step is recorded, so any piece can be traced back to the tap that started it."}]},
"gold":{"name":"Gold","lead":0.6,"tail":1.4,"vo":[
 {"id":"split","text":"Then the light is split again, this time into business domains: teaching, students, research and finance."},
 {"id":"products","text":"Each domain holds many data products. Think of them as paintings."},
 {"id":"subject","text":"The subject is the domain. The style is what the audience needs."},
 {"id":"analysts","text":"Analysts get every detail."},
 {"id":"execs","text":"Executives get the essence, in a few bold shapes."},
 {"id":"reports","text":"Government reports get a painting made by strict rules, like counting students on census date."},
 {"id":"live","text":"Live operations get a quick impression of right now."},
 {"id":"marts","text":"In dbt, each painting is a mart with a contract and an owner: a data product."},
 {"id":"exposure","text":"And its label is an exposure, recording where the painting is shown, and to whom."},
 {"id":"gold","text":"That's gold."}]},
"layers":{"name":"The layers together","lead":0.6,"tail":1.4,"vo":[
 {"id":"back","text":"Step back, and the whole system comes into view."},
 {"id":"appdom","text":"Application domains flow in on one side."},
 {"id":"bsg","text":"Bronze keeps what arrived. Silver makes it consistent. Gold makes it useful."},
 {"id":"busdom","text":"Business domains flow out on the other, into dashboards, apps and Genie."},
 {"id":"dbtgov","text":"dbt governs every step, from source to exposure, and its lineage maps every connection."},
 {"id":"dbx","text":"And the Databricks lakehouse runs and stores it all, governed by Unity Catalog."}]},
"meaning":{"name":"Meaning","lead":0.6,"tail":1.6,"vo":[
 {"id":"noise","text":"But pictures without meaning are just noise."},
 {"id":"bricks","text":"The platform is the bricks. Meaning is the shared language."},
 {"id":"catalog","text":"In the dbt Catalog, anyone can read what each picture shows, where it came from, and who owns it."},
 {"id":"define","text":"Words are defined once: an enrolled student is one still enrolled on census date."},
 {"id":"uc","text":"Unity Catalog marks trusted data as certified, decides who can see what, and masks personal details."},
 {"id":"knowledge","text":"And a university's knowledge lives everywhere: intranet pages, policy libraries, the handbook, process maps."},
 {"id":"mcp","text":"Through MCP, a standard plug that lets AI connect to other systems,"},
 {"id":"reads","text":"the platform reads those sources where they live, with your permissions."},
 {"id":"onto","text":"Together with the sketch, they become one map of meaning: Genie Ontology."}]},
"speeds":{"name":"Two speeds","lead":0.6,"tail":1.4,"vo":[
 {"id":"now","text":"Some questions need one answer, right now: is there still a seat in Tuesday's 9 am class?"},
 {"id":"years","text":"Others need every record, over years: which classes fill up first?"},
 {"id":"jobs","text":"Different jobs, different engines."},
 {"id":"lake","text":"Lakebase, a Postgres database built into the platform, gives apps a fast desk copy of what they need,"},
 {"id":"sync","text":"kept in sync automatically, with changes flowing back."}]},
"out":{"name":"Ways out","lead":0.6,"tail":1.6,"vo":[
 {"id":"four","text":"Now the pictures go out, four ways."},
 {"id":"events","text":"Events: when something changes, the integration platform rings a bell, and each system comes back for exactly what it needs."},
 {"id":"sql","text":"SQL endpoints: a reading room where tools can scan millions of records for big questions."},
 {"id":"copies","text":"Copies: for older systems that can't read the originals, the integration platform delivers copies."},
 {"id":"stale","text":"Useful, but every copy has to be kept up to date."},
 {"id":"twist","text":"And the fourth way changes everything.","pause":1.0},
 {"id":"projector","text":"A projector shows the original somewhere else, without making a copy."},
 {"id":"share","text":"OpenSharing projects live research data to a partner university."},
 {"id":"mirror","text":"Mirroring lets Microsoft Fabric see the same pictures in place."},
 {"id":"fed","text":"Federation turns the projector around, so we can see other systems where they live."},
 {"id":"one","text":"One original. No copies to keep in sync."}]},
"people":{"name":"Apps and Genie","lead":0.6,"tail":1.8,"vo":[
 {"id":"two","text":"People meet the data in two ways."},
 {"id":"app","text":"Apps: a Databricks App shows an officer a student's record,"},
 {"id":"fix","text":"she fixes a wrong degree code, and the correction flows straight back into the platform."},
 {"id":"genie","text":"And conversation: Genie."},
 {"id":"ask","text":"Ask: which first-year classes need more seats next semester?"},
 {"id":"answer","text":"A Genie Agent answers with certified numbers and shows its sources, guided by Genie Ontology."},
 {"id":"perms","text":"And it only shows you what you're allowed to see."}]},
"end":{"name":"Pull back","lead":0.5,"tail":4.2,"vo":[
 {"id":"recap","text":"One tap became a snapshot, then a clear picture, and finally a decision:"},
 {"id":"seats","text":"a new class opens, and 140 more students get a seat."},
 {"id":"tag","text":"Move less. Mean more.","gap":0.4}]}
};
