"""Writes each domain's definitions and seeds/reference/shared/key_sets.csv from the conceptual model.

The meaning is written once, in the conceptual model: one file per domain, next to its core models
(models/core/<domain>/_<domain>__conceptual.yml), and a shared one for the key sets
(models/_shared/_shared__conceptual.yml). This script turns each domain's entities and
relationships into doc blocks in _<domain>__definitions.md, next to its conceptual model; the dbt
YAML shows them with doc(), and on Databricks persist_docs pushes them to Unity Catalog. The seed
the models join to is generated from the key sets.

    python scripts/definitions.py           # write the definitions and the key sets seed
    python scripts/definitions.py --check   # fail if any is out of date
"""
import argparse
import csv
import io
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCES = sorted((ROOT / "models").glob("**/_*__conceptual.yml"))
KEY_SETS = ROOT / "seeds" / "reference" / "shared" / "key_sets.csv"


def one_line(text):
    return " ".join(str(text).split())


def block(name, title, item):
    lines = ["{% docs " + name + " %}", f"**{title}.** {one_line(item['definition'])}", ""]
    key = item.get("business_key")
    if key:
        issued = f" Issued by: {one_line(key['issued_by'])}." if key.get("issued_by") else ""
        lines.append(f"- Business key: {one_line(key['rule'])}{issued}")
    if item.get("owner"):
        lines.append(f"- Owner of the meaning: {item['owner']}.")
    for kind in item.get("kinds", []):
        text = f" {one_line(kind['definition'])}" if kind.get("definition") else ""
        lines.append(f"- Kind: {kind['name']}.{text} Owner: {kind['owner']}.")
    for rule in item.get("identity", []):
        lines.append(f"- Identity: {one_line(rule)}")
    for rule in item.get("rules", []):
        lines.append(f"- Rule: {one_line(rule)}")
    if item.get("history"):
        lines.append(f"- History: {one_line(item['history'])}")
    lines.append("{% enddocs %}")
    return "\n".join(lines)


def target(source):
    return source.with_name(source.name.replace("__conceptual.yml", "__definitions.md"))


def render(source):
    model = yaml.safe_load(source.read_text())
    parts = [
        f"# {model['domain'].capitalize()} domain: definitions",
        "",
        f"*Generated by `scripts/definitions.py` from `{source.name}`, next to this file. Edit the "
        "conceptual model, then run the script; don't edit this file.*",
        "",
    ]
    for entity in model.get("entities", []):
        parts += [block(entity["name"], entity["name"].capitalize(), entity), ""]
    for relationship in model.get("relationships", []):
        if relationship.get("owner"):
            title = relationship.get("label", relationship["name"]).capitalize()
            parts += [block(relationship["name"], title, relationship), ""]
    return "\n".join(parts)


def render_key_sets():
    key_sets = {}
    for source in SOURCES:
        for key_set in yaml.safe_load(source.read_text()).get("key_sets", []):
            if key_set["code"] in key_sets:
                raise SystemExit(f"key set {key_set['code']} is defined twice: write it once")
            key_sets[key_set["code"]] = key_set
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(["key_set", "system_name", "owner"])
    for key_set in key_sets.values():
        writer.writerow([one_line(key_set[field]) for field in ("code", "system", "owner")])
    return out.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a generated file is out of date")
    args = parser.parse_args()
    outputs = {target(source): render(source) for source in SOURCES
               if yaml.safe_load(source.read_text()).get("domain")}
    outputs[KEY_SETS] = render_key_sets()
    if args.check:
        stale = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
        for path in stale:
            print(f"{path.relative_to(ROOT)} is out of date: run python scripts/definitions.py", file=sys.stderr)
        if stale:
            return 1
        print("the definitions and seeds/reference/shared/key_sets.csv are up to date")
        return 0
    for path, text in outputs.items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
