"""Writes docs/definitions.md: one dbt doc block per entity and relationship, from model/conceptual.yml.

The meaning is written once, in the conceptual model. This script turns it into doc blocks, the
dbt YAML shows them with doc(), and on Databricks persist_docs pushes them to Unity Catalog.

    python scripts/definitions.py           # write docs/definitions.md
    python scripts/definitions.py --check   # fail if docs/definitions.md is out of date
"""
import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "model" / "conceptual.yml"
TARGET = ROOT / "docs" / "definitions.md"


def one_line(text):
    return " ".join(str(text).split())


def block(name, title, item):
    lines = ["{% docs " + name + " %}", f"**{title}.** {one_line(item['definition'])}", ""]
    key = item.get("business_key")
    if key:
        issued = f" Issued by: {one_line(key['issued_by'])}." if key.get("issued_by") else ""
        lines.append(f"- Business key: {one_line(key['rule'])}{issued}")
    if item.get("owner"):
        lines.append(f"- Owner of the meaning: {item['owner']}.")
    for kind in item.get("kinds", []):
        text = f" {one_line(kind['definition'])}" if kind.get("definition") else ""
        lines.append(f"- Kind: {kind['name']}.{text} Owner: {kind['owner']}.")
    for rule in item.get("identity", []):
        lines.append(f"- Identity: {one_line(rule)}")
    for rule in item.get("rules", []):
        lines.append(f"- Rule: {one_line(rule)}")
    if item.get("history"):
        lines.append(f"- History: {one_line(item['history'])}")
    lines.append("{% enddocs %}")
    return "\n".join(lines)


def render():
    model = yaml.safe_load(SOURCE.read_text())
    parts = [
        "# Definitions",
        "",
        "*Generated by `scripts/definitions.py` from `model/conceptual.yml`. Edit the conceptual model, "
        "then run the script; don't edit this file.*",
        "",
    ]
    for entity in model["entities"]:
        parts += [block(entity["name"], entity["name"].capitalize(), entity), ""]
    for relationship in model["relationships"]:
        if relationship.get("owner"):
            title = relationship.get("label", relationship["name"]).capitalize()
            parts += [block(relationship["name"], title, relationship), ""]
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if docs/definitions.md is out of date")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print("docs/definitions.md is out of date: run python scripts/definitions.py", file=sys.stderr)
            return 1
        print("docs/definitions.md is up to date")
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
