"""Writes docs/physical.md: the physical model of the core and marts, as a Mermaid diagram, from
target/manifest.json. The conceptual diagram is drawn by hand; this one is generated, so it
can't drift from the YAML.

    dbt parse --profiles-dir .
    python scripts/diagrams.py           # write docs/physical.md
    python scripts/diagrams.py --check   # fail if docs/physical.md is out of date
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "physical.md"
LAYERS = ("core", "marts")


def entity_name(node):
    return node["name"] + (f"_v{node['version']}" if node.get("version") is not None else "")


def is_latest(node):
    return node.get("version") is None or str(node["version"]) == str(node.get("latest_version"))


def first_sentence(text):
    text = " ".join((text or "").split())
    match = re.match(r"(.+?[.:])(\s|$)", text)
    return (match.group(1) if match else text).rstrip(":.") + "."


def primary_key(node):
    for constraint in node.get("constraints", []):
        if constraint["type"] == "primary_key":
            return list(constraint["columns"])
    return [name for name, column in node["columns"].items()
            if any(c["type"] == "primary_key" for c in column.get("constraints", []))]


def ref_name(expression):
    match = re.search(r"ref\(\s*['\"]([^'\"]+)['\"]", expression or "")
    return match.group(1) if match else None


def load(manifest_path):
    manifest = json.loads(Path(manifest_path).read_text())
    models = {}
    deprecated = []
    for node in manifest["nodes"].values():
        if node["resource_type"] != "model" or node["fqn"][1] not in LAYERS:
            continue
        if not is_latest(node):
            deprecated.append(node)
            continue
        models[node["name"]] = node

    unique_columns = {}
    for node in manifest["nodes"].values():
        meta = node.get("test_metadata") or {}
        if node["resource_type"] == "test" and meta.get("name") == "unique":
            parent = manifest["nodes"].get(node.get("attached_node") or "", {})
            unique_columns.setdefault(parent.get("name"), set()).add(node.get("column_name"))

    edges = set()
    for node in manifest["nodes"].values():
        meta = node.get("test_metadata") or {}
        if node["resource_type"] != "test" or meta.get("name") != "relationships":
            continue
        child = manifest["nodes"].get(node.get("attached_node") or "")
        parent = ref_name(meta["kwargs"].get("to"))
        if child and is_latest(child) and child["name"] in models and parent in models:
            edges.add((parent, meta["kwargs"].get("field"), child["name"], node.get("column_name")))
    for child in models.values():
        for name, column in child["columns"].items():
            for constraint in column.get("constraints", []):
                parent = ref_name(constraint.get("to"))
                if constraint["type"] == "foreign_key" and parent in models:
                    edges.add((parent, constraint["to_columns"][0], child["name"], name))
    return models, deprecated, unique_columns, sorted(edges)


def render(manifest_path):
    models, deprecated, unique_columns, edges = load(manifest_path)
    order = sorted(models.values(), key=lambda n: (LAYERS.index(n["fqn"][1]), n["name"]))
    foreign = {(child, column) for _, _, child, column in edges}

    lines = ["```mermaid", "erDiagram"]
    for node in order:
        pk = primary_key(node)
        lines.append(f"    {entity_name(node)} {{")
        for name, column in node["columns"].items():
            data_type = re.sub(r"\W+", "_", column.get("data_type") or "unknown").strip("_")
            marks = (["PK"] if name in pk else []) + (["FK"] if (node["name"], name) in foreign else [])
            lines.append(f"        {data_type} {name}{' ' + ', '.join(marks) if marks else ''}")
        lines.append("    }")
    for parent, field, child, column in edges:
        parent_node = models[parent]
        one = primary_key(parent_node) == [field] or field in unique_columns.get(parent, set())
        left = "||" if one else "}|"
        lines.append(f'    {entity_name(parent_node)} {left}--o{{ {entity_name(models[child])} : "{column}"')
    lines.append("```")

    table = ["| Model | Grain | Access | Contract |", "|---|---|---|---|"]
    for node in order:
        contract = "enforced" if node["config"].get("contract", {}).get("enforced") else "none"
        table.append(f"| `{entity_name(node)}` | {first_sentence(node['description'])} | "
                     f"{node['config'].get('access') or node.get('access')} | {contract} |")

    parts = [
        "# Physical model",
        "",
        "*Generated by `scripts/diagrams.py` from `target/manifest.json`. Don't edit this file: change "
        "the YAML, run `dbt parse`, then run the script. CI fails if it's out of date.*",
        "",
        "The core (the enterprise contract) and the marts (the consumer contracts), at their latest "
        "versions: every column with its contracted type, primary keys (PK), and the relationships "
        "the tests check (FK). `||--o{` points from a key that is unique; `}|--o{` from a key that "
        "has versions, so several rows share it.",
        "",
        *lines,
        "",
        *table,
        "",
    ]
    if deprecated:
        parts += ["Older versions still built, until their deprecation date:", ""]
        for node in sorted(deprecated, key=entity_name):
            parts.append(f"- `{entity_name(node)}`: deprecated on {str(node.get('deprecation_date'))[:10]}.")
        parts.append("")
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--manifest", default=str(ROOT / "target" / "manifest.json"))
    parser.add_argument("--check", action="store_true", help="fail if docs/physical.md is out of date")
    args = parser.parse_args()
    if not Path(args.manifest).exists():
        print(f"{args.manifest} not found: run dbt parse first", file=sys.stderr)
        return 2
    text = render(args.manifest)
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != text:
            print("docs/physical.md is out of date: run dbt parse, then python scripts/diagrams.py", file=sys.stderr)
            return 1
        print("docs/physical.md is up to date")
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
