"""Writes each domain's definitions, the university's map and the key sets seed from the conceptual model.

The meaning is written once, in the conceptual model:
- one file per core domain and per mart, next to its models
  (models/core/<domain>/_<domain>__conceptual.yml, models/marts/<consumer>/_<consumer>__conceptual.yml).
  This script turns its entities and relationships into doc blocks in _<domain>__definitions.md,
  next to it; the dbt YAML shows them with doc(), and on Databricks persist_docs pushes them to
  Unity Catalog.
- the university's map (models/_shared/_shared__conceptual.yml): its domains and their key
  entities. This script draws the map into _shared__conceptual.md.

The key sets are written once too, on the source that issues each (meta.key_set in
sources/<system>/_<system>__sources.yml); this script writes them into the seed the models join to.

It also checks that they agree: every entity a domain defines is on the map as modelled, under
that domain, and every modelled entity on the map is defined; every entity a mart uses is defined
in a core domain, and every mart states its question; the map's relationships name entities on
it; the map keeps to its maximum.

    python scripts/generate/definitions.py           # write the definitions and the key sets seed
    python scripts/generate/definitions.py --check   # fail if any is out of date
"""
import argparse
import csv
import io
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SOURCES = sorted((ROOT / "models").glob("**/_*__conceptual.yml"))
KEY_SETS = ROOT / "seeds" / "reference" / "shared" / "key_sets.csv"
MAP = ROOT / "models" / "_shared" / "_shared__conceptual.yml"
SOURCE_FILES = sorted((ROOT / "sources").glob("*/_*__sources.yml"))


def one_line(text):
    return " ".join(str(text).split())


def block(name, title, item):
    lines = ["{% docs " + name + " %}", f"**{title}.** {one_line(item['definition'])}", ""]
    key = item.get("business_key")
    if key:
        issued = f" Issued by: {one_line(key['issued_by'])}." if key.get("issued_by") else ""
        lines.append(f"- Business key: {one_line(key['rule'])}{issued}")
    if item.get("owner"):
        lines.append(f"- Owner of the meaning: {item['owner']}.")
    for kind in item.get("kinds", []):
        text = f" {one_line(kind['definition'])}" if kind.get("definition") else ""
        lines.append(f"- Kind: {kind['name']}.{text} Owner: {kind['owner']}.")
    for rule in item.get("identity", []):
        lines.append(f"- Identity: {one_line(rule)}")
    for rule in item.get("rules", []):
        lines.append(f"- Rule: {one_line(rule)}")
    if item.get("history"):
        lines.append(f"- History: {one_line(item['history'])}")
    lines.append("{% enddocs %}")
    return "\n".join(lines)


def target(source):
    return source.with_name(source.name.replace("__conceptual.yml", "__definitions.md"))


def render(source):
    model = yaml.safe_load(source.read_text())
    parts = [
        f"# {model['domain'].capitalize()}{'' if model.get('kind') == 'mart' else ' domain'}: definitions",
        "",
        f"*Generated by `scripts/generate/definitions.py` from `{source.name}`, next to this file. Edit the "
        "conceptual model, then run the script; don't edit this file.*",
        "",
    ]
    for entity in model.get("entities", []):
        parts += [block(entity["name"], entity.get("label", entity["name"]).capitalize(), entity), ""]
    for relationship in model.get("relationships", []):
        if relationship.get("owner"):
            title = relationship.get("label", relationship["name"]).capitalize()
            parts += [block(relationship["name"], title, relationship), ""]
    return "\n".join(parts)


def render_key_sets():
    key_sets = {}
    for path in SOURCE_FILES:
        for source in yaml.safe_load(path.read_text()).get("sources", []):
            key_set = (source.get("config", {}).get("meta") or {}).get("key_set")
            if not isinstance(key_set, dict):
                raise SystemExit(f"source {source['name']} has no key set: give it meta.key_set, with code, system and owner")
            if key_set["code"] in key_sets:
                raise SystemExit(f"key set {key_set['code']} is defined twice: write it once")
            key_sets[key_set["code"]] = key_set
    out = io.StringIO()
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(["key_set", "system_name", "owner"])
    for key_set in key_sets.values():
        writer.writerow([one_line(key_set[field]) for field in ("code", "system", "owner")])
    return out.getvalue()


def defined(model):
    """The names a domain's file defines: its entities, and the relationships it owns."""
    return ({entity["name"] for entity in model.get("entities", [])}
            | {r["name"] for r in model.get("relationships", []) if r.get("owner")})


def validate(the_map, domains):
    problems = []
    on_map = {e["name"]: (d["name"], e["status"]) for d in the_map["domains"] for e in d["entities"]}
    if len(on_map) > the_map["max_entities"]:
        problems.append(f"the map has {len(on_map)} entities: keep it to {the_map['max_entities']}")
    core = {name: model for name, model in domains.items() if model.get("kind") != "mart"}
    core_defined = set()
    for name, model in core.items():
        for entity in defined(model):
            core_defined.add(entity)
            if on_map.get(entity) != (name, "modelled"):
                problems.append(f"{entity} is defined in the {name} domain: put it on the map, under {name}, as modelled")
    for entity, (domain, status) in on_map.items():
        if status == "modelled" and entity not in defined(core.get(domain, {})):
            problems.append(f"{entity} is modelled on the map: define it in the {domain} domain's conceptual model")
    for name, model in domains.items():
        if model.get("kind") == "mart" and not (model.get("question") or {}).get("text"):
            problems.append(f"the {name} mart has no question: write it under question:, with asked_by, text and decision")
        for entity in model.get("uses", []):
            if entity not in core_defined:
                problems.append(f"the {name} mart uses {entity}, which no core domain defines")
    for left, _, right in the_map["relationships"]:
        for entity in (left, right):
            if entity not in on_map:
                problems.append(f"the map's relationship names {entity}, which isn't on the map")
    if problems:
        raise SystemExit("the conceptual model doesn't agree with itself:\n- " + "\n- ".join(problems))


def node(name):
    # Prefixed, so an entity called class or end can't clash with Mermaid's keywords.
    return f"e_{name}"


def render_map(the_map, domains):
    lines = ["```mermaid", "flowchart TB"]
    modelled = []
    for domain in the_map["domains"]:
        lines.append(f'    subgraph d_{domain["name"]}["{domain["name"].capitalize()}"]')
        for entity in domain["entities"]:
            label = entity["name"].replace("_", " ").capitalize()
            lines.append(f'        {node(entity["name"])}["{label}"]')
            if entity["status"] == "modelled":
                modelled.append(node(entity["name"]))
        lines.append("    end")
    for left, label, right in the_map["relationships"]:
        lines.append(f'    {node(left)} -- "{label}" --> {node(right)}')
    lines += [
        "    classDef modelled stroke-width:3px",
        "    classDef planned stroke-dasharray: 4 3",
        f"    class {','.join(modelled)} modelled",
        "    class " + ",".join(node(e["name"]) for d in the_map["domains"] for e in d["entities"]
                              if e["status"] == "planned") + " planned",
        "```",
    ]
    table = ["| Domain | Owner | Entity | Status | Reference (TCSI) |", "|---|---|---|---|---|"]
    for domain in the_map["domains"]:
        for entity in domain["entities"]:
            name = entity["name"]
            if entity["status"] == "modelled":
                name = f"[{name}](../core/{domain['name']}/_{domain['name']}__conceptual.yml)"
            table.append(f"| {domain['name']} | {domain['owner']} | {name} | {entity['status']} | "
                         f"{one_line(entity['reference'])} |")
    consumers = ["| Consumer | Asked by | Question | Uses |", "|---|---|---|---|"]
    for name, model in sorted(domains.items()):
        if model.get("kind") == "mart":
            question = model["question"]
            consumers.append(f"| [{name}](../marts/{name}/_{name}__conceptual.yml) | {question['asked_by']} | "
                             f"{one_line(question['text'])} | {', '.join(model['uses'])} |")
    count = sum(len(d["entities"]) for d in the_map["domains"])
    return "\n".join([
        "# The university's conceptual model",
        "",
        "*Generated by `scripts/generate/definitions.py` from `_shared__conceptual.yml`, next to this "
        "file. Edit the map, then run the script; don't edit this file.*",
        "",
        f"The university's domains and their key entities, at a high level: {count} of at most "
        f"{the_map['max_entities']}. The domains follow the reference model, TCSI. A thick border is "
        "modelled in this project; a dashed one is planned. Each modelled domain has its own conceptual "
        "model, with the detail, in its folder.",
        "",
        *lines,
        "",
        *table,
        "",
        "## Consumers",
        "",
        "Each consumer has its own conceptual model: the question it asks, and what it adds to the core.",
        "",
        *consumers,
        "",
    ])


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if a generated file is out of date")
    args = parser.parse_args()
    domains = {}
    for source in SOURCES:
        model = yaml.safe_load(source.read_text())
        if model.get("domain"):
            domains[model["domain"]] = model
    the_map = yaml.safe_load(MAP.read_text())
    validate(the_map, domains)
    outputs = {target(source): render(source) for source in SOURCES
               if yaml.safe_load(source.read_text()).get("domain")}
    outputs[MAP.with_suffix(".md")] = render_map(the_map, domains)
    outputs[KEY_SETS] = render_key_sets()
    if args.check:
        stale = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
        for path in stale:
            print(f"{path.relative_to(ROOT)} is out of date: run python scripts/generate/definitions.py", file=sys.stderr)
        if stale:
            return 1
        print("the definitions, the map and seeds/reference/shared/key_sets.csv are up to date")
        return 0
    for path, text in outputs.items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
